service: aws-node-crud
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-2
  iam:
    role:
      statements:  
        - Effect: Allow
          Action: 
            - dynamodb:*
            - ses:*
            - sns:*
            - ssm:*
          Resource: 
            - arn:aws:dynamodb:us-west-2:058264440990:table/usuarios   
            - "*"
          

functions:
  getUsers:
    handler: src/user.getUsers
    events:
      - httpApi:
          path: /users
          method: get
  addUser:
    handler: src/user.addUser
    events:
      - httpApi:
          path: /users
          method: post
  updateUser:
    handler: src/user.updateUser
    events:
      - httpApi:
          path: /users/{id}
          method: put
  deleteUser:
    handler: src/user.deleteUser
    events:
      - httpApi:
          path: /users/{id}
          method: delete
  snsManager:
    handler: src/user.sns
    events:
      - sns: email
  email:
    handler: src/user.email
    events:
      - httpApi:
          path: /email
          method: post

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: usuarios
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    snsEmails:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: "snsemails"

plugins:
  - serverless-offline          